services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: innoscripta-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: innoscripta-client
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  node_modules:

